name: Check Merge

on:
  pull_request:
    types: [labeled]

jobs:
  merge-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check PR Label for Merge Readiness
        id: check-label
        run: |
          if [[ "${{ toJSON(github.event.pull_request.labels) }}" != *"ready-to-merge"* ]]; then
            echo "Not ready for merge. Exiting."
            exit 1
          fi
##3#
