name: Check Review

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  review-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for reviews
        uses: actions/github-script@v6
        with:
          script: |
            if (!context || !context.payload || !context.payload.pull_request) {
              core.setFailed('This workflow is only applicable to pull requests.');
              return;
            }

            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const approvedReviews = reviews.filter(
              review => review.state === 'APPROVED'
            );

            if (approvedReviews.length < 2) {
              core.setFailed(`PR requires at least 2 approvals. Found ${approvedReviews.length}.`);
            }
