name: Check Review

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  review-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for reviews
        uses: Betrand1999/github-action/path-to-action@version
        with:
          minimum-approvals: 2  # Modify this based on your requirements
          review-type: APPROVED
