name: Check Review

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  review-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for reviews
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');

            // Check if context is available and contains the necessary PR information
            if (!context || !context.payload || !context.payload.pull_request) {
              core.setFailed('This workflow is only applicable to pull requests.');
              return;
            }

            try {
              // Fetch pull request reviews
              const { data: reviews } = await github.rest.pulls.listReviews({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
              });

              // Filter to find approved reviews
              const approvedReviews = reviews.filter(
                review => review.state === 'APPROVED'
              );

              // Check if the required number of approvals is met
              const requiredApprovals = 2;
              if (approvedReviews.length < requiredApprovals) {
                core.setFailed(`PR requires at least ${requiredApprovals} approvals. Found ${approvedReviews.length}.`);
              } else {
                core.info(`PR has met the required number of approvals: ${approvedReviews.length}`);
              }
            } catch (error) {
              core.setFailed(`An error occurred while checking reviews: ${error.message}`);
            }
