name: Deploy Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/actions/runner:ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t app .

      - name: Cleanup Docker containers
        if: always()  # Ensures this runs even if the previous steps fail
        run: |
          docker ps -q | xargs -r docker stop
          docker ps -a -q | xargs -r docker rm
