name: Deploy Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/actions/runner:ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t app .

    
