name: Deploy Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    container:
      image: betrand1997/github-action-images-with-dependencies
      options: --network bridge  # Specify network option if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t app .