name: CICD BUILD AND PUSH DOCKER IMAGE 
on:
 push:
   branches:
     - main
jobs:
  build:
   runs-on: ubuntun-latest
   steps:
     - name: checkout repo 
       uses: actions/checkout@v2 
     - name: login to docker 
       uses: docker/login@v2
       with:
          username: ${secrets.DOCKER_USERNAME}
          password: ${{secrets.DOCKER_PASSWORD}}
     - name: pull image 
       run: docker pull nginx 
     - name: run image 
       run: docker run -d -p 8080:90 --name my_container nginx 
     - name: tag image 
       run: docker tag nginx:latest betrand1997/nginx:latest 
     - name: push image 
       run: docker push betrand1997/nginx:latest 
