name: CICD BUILD AND RUN CUSTOM DOCKER IMAGE 

on:
  push:
    branches:
      - main

jobs:
  infra-dev-dryrun:
    if: github.event_name != 'push' || '' == 'True' || '' == 'True'
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: betrand1997/nginx
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}  
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  
      options: "--user root"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run command
        run: docker ps && docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull image
        run: docker pull nginx

      - name: Run image
        run: docker run -d -p 8080:90 --name my_container nginx

      - name: Tag image
        run: docker tag nginx:latest betrand1997/nginx:latest

      - name: Push image
        run: docker push betrand1997/nginx:latest
