name: Run commans
on:
 push:
   branches:
     - main 

jobs:
  command-job:
   runs-on: self-hosted
   environment: dev
   steps:
     - name: Run action to check repo
       uses: actions/checkout@v4
     - name: Run command 
       run: echo "Hello world "
     - name: Run multi commands 
       run: |
         echo "Hello man "
         echo "Hello man "
         echo "Hello man "
         echo "Hello man "


       