name: Build job

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment to run in'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - production

jobs:
  dev-run-job:
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run command 
        run: echo "Hello world"

      - name: Run multi commands 
        run: |
          echo "Hello man"
          echo "Hello man"
          echo "Hello man"
          echo "Hello man"
