name: Build job

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment to run in'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - production

jobs:
  dev-run-job:
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: run command
        run: echo "Hello world"
    
