name: BUILD AND PUSH IMAGE TO DOCKER HUB
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: betrand1997/myapp
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build container
        run: docker build -t test .

      - name: Tag container
        run: docker tag test betrand1999/test

      - name: Push container to Docker Hub
        run: docker push betrand1999/test

      - name: Run container
        run: docker run -d -p 8080:80 betrand1999/test

      - name: Check if container is running
        run: docker ps

        ###
