name: BUILD AND PUSH IMAGE TO DOCKER HUB
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:stable-dind  # Use Docker-in-Docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build container
        run: docker build -t betrand1997/test .

      - name: Tag container
        run: docker tag betrand1997/test betrand1997/test:latest

      - name: Push container to Docker Hub
        run: docker push betrand1997/test:latest

      - name: Run container
        run: docker run -d -p 8080:80 betrand1997/test:latest

      - name: Check if container is running
        run: docker ps
