name: CICD BUILD AND PUSH IMAGE
on:
 push:
   branches:
     - dev
jobs:
  build:
   runs-on: ubuntu
   container:
    image: betrand1997/myapp  
   steps:
     - name: checkout repo
       run: actions/checkout@v2
     - name: run a command
       run: echo "Testing workflow"