name: CICD BUILD AND PUSH IMAGE
on:
 push:
   branches:
     - dev
jobs:
  build:
   runs-on: ubuntu-latest
   container:
    image: betrand1997/myapp  
   steps:
     - name: checkout repo
       uses: actions/checkout@v2
     - name: run a command
       run: echo "Testing workflow"
     - name: Print environment info
       run: uname -a
   